apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-harbor-jobservice-pv
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /var/openebs/local/harbor-jobservice-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-node2

