apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: jenkins-webhook-sensor
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: github-push-dep
      eventSourceName: webhook-event-source
      eventName: github-push
  triggers:
    - template:
        name: jenkins-trigger
        http:
          url: "http://192.168.30.11:32589/job/gitops-pipeline/build"
          method: POST
          basicAuth:
            username:
              secret:
                name: jenkins-auth
                key: username
            password:
              secret:
                name: jenkins-auth
                key: api-token
          headers:
            Jenkins-Crumb: "339b28370a448f5ba6a72d4301b8ac401d45931d672ce9d36bc6ae96300030e3"

