apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook-event-source
  namespace: argo-events
spec:
  webhook:
    github-push:
      port: "12000"
      endpoint: /github-push
      method: POST

