apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

patches:
  - path: rollout-patch.yaml
  - path: hpa-patch.yaml
  - path: ingress-patch.yaml

images:
  - name: 192.168.30.11:30003/library/mcp-hr-server:latest
    newTag: v1.0.0

configMapGenerator:
  - name: myapp-config
    behavior: merge
    literals:
      - app_env=staging
      - log_level=info
      - max_requests=500
