apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: mcp-hr-chaos-engine    # 必须与 Jenkinsfile 中 CHAOS_ENGINE_NAME 一致
  namespace: staging
spec:
  engineState: "active"        # active 表示立即启动实验
  annotationCheck: "false"     # 关闭注解检查
  appinfo:
    appns: "staging"           # 目标应用所在命名空间
    applabel: "app.kubernetes.io/name=myapp"   # 必须与你的应用 Pod 标签一致
    appkind: "deployment"      # 你的应用资源类型：deployment / statefulset / daemonset
  chaosServiceAccount: litmus-admin   # 使用上一步创建的 ServiceAccount
  jobCleanUpPolicy: 'delete'   # 实验结束后清理资源
  experiments:
    - name: pod-delete         # 实验名称：删除 Pod
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: '30'          # 混沌实验持续 30 秒
            - name: CHAOS_INTERVAL
              value: '10'          # 每 10 秒执行一次删除
            - name: FORCE
              value: 'false'       # 优雅删除（true 为强制删除）
            - name: PODS_AFFECTED_PERC
              value: '100'         # 影响 100% 的 Pod
