- op: replace
  path: /metadata/annotations/nginx.ingress.kubernetes.io~1ssl-redirect
  value: "true"
- op: add
  path: /metadata/annotations/nginx.ingress.kubernetes.io~1rewrite-target
  value: /
- op: add
  path: /metadata/annotations/cert-manager.io~1cluster-issuer
  value: letsencrypt-prod
- op: add
  path: /spec/tls
  value:
    - hosts:
        - myapp.example.com
      secretName: myapp-tls-prod
