apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

patches:
  - target:
      kind: Rollout
      name: myapp
    path: rollout-patch.yaml
  - target:
      kind: HorizontalPodAutoscaler
      name: myapp-hpa
    path: hpa-patch.yaml
  - target:
      kind: Ingress
      name: myapp
    path: ingress-patch.yaml
  - path: networkpolicy.yaml

images:
  - name: 192.168.30.11:30003/library/mcp-hr-server
    newTag: v2

configMapGenerator:
  - name: myapp-config
    behavior: merge
    literals:
      - app_env=production
      - log_level=warn
      - max_requests=5000
